### ISSUE TITLE
build failure on centos 7: Qt QSslError class error

### ISSUE THREAD

**Issue by fjallraven** [AcademySoftwareFoundation/OpenRV#33]
Hello

I'm building under Centos 7.9, followed the build steps, just built opensource version of qt (qt-everywhere-src-5.15.2)

Build almost makes it, just hit this error. Any ideas?

```
/qt_build/include/QtNetwork/qnetworkaccessmanager.h:65:7: note: forward declaration of ‘class QSslError’
   65 | class QSslError;
      |       ^~~~~~~~~
In file included from /qt_build/include/QtCore/qhash.h:46,
                 from /qt_build/include/QtCore/qshareddata.h:46,
                 from /qt_build/include/QtCore/QSharedDataPointer:1,
                 from /qt_build/include/QtNetwork/qnetworkrequest.h:44,
                 from /qt_build/include/QtNetwork/qnetworkaccessmanager.h:44,
                 from /qt_build/include/QtNetwork/QNetworkAccessManager:1,
                 from /OpenRV/src/lib/mu/MuQt5/MuQt5/RvNetworkAccessManager.h:9,
                 from /OpenRV/src/lib/mu/MuQt5/RvNetworkAccessManager.cpp:7:
/qt_build/include/QtCore/qlist.h:511:51: error: invalid use of incomplete type ‘class QSslError’
  511 |                 (reinterpret_cast<T*>(current))->~T();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
In file included from /qt_build/include/QtNetwork/QNetworkAccessManager:1,
                 from /OpenRV/src/lib/mu/MuQt5/MuQt5/RvNetworkAccessManager.h:9,
                 from /OpenRV/src/lib/mu/MuQt5/RvNetworkAccessManager.cpp:7:
/qt_build/include/QtNetwork/qnetworkaccessmanager.h:65:7: note: forward declaration of ‘class QSslError’
   65 | class QSslError;
      |       ^~~~~~~~~
make[2]: *** [src/lib/mu/MuQt5/CMakeFiles/MuQt5.dir/build.make:924: src/lib/mu/MuQt5/CMakeFiles/MuQt5.dir/RvNetworkAccessManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8039: src/lib/mu/MuQt5/CMakeFiles/MuQt5.dir/all] Error 2
```

```
-- Using Boost:        1.76.0
-- Using Dav1d:        1.0.0
-- Using FFMPEG:       n4.4.3
-- Using GC:           8.2.2
-- Using GLEW:         2.2.0
-- Using Imath:        3.1.5
-- Using OpenEXR:      3.1.5
-- Using Python3:      3.9.15
-- Using PySide2:      5.15.2.1
-- Using Qt5:          5.15.2
-- Using zlib:         1.2.13
```
Thank you

**Comment by geffrak** [comment]
Have you compiled Qt with SSL support? Why did you compiled Qt instead of taking the pre-compiled package from their online installer?

**Comment by chadrik** [comment]
We have our own internal build of qt, so I also ran into this problem. To fix it you need to rebuild qt with ssl support, but the catch is that it will only accept openssl 1.1.  For us on CentOS 7.8 that was a problem because openssl 1.0 is standard.  I think this is the same for 7.9, because I read that 1.1 only became the default in CentOS 8.0.  

Here's how I fixed my qt build:

- `yum install openssl11-devel`
- add these flags to `./configure`:
  ```
   -openssl linked
   OPENSSL_LINKDIR=/usr/include/openssl11/
   OPENSSL_LIBS='-l:libssl.so.1.1 -l:libcrypto.so.1.1
  ```
- rebuild

Recompiling rv with this new build of qt succeeded.  Hope that helps.

**Comment by chadrik** [comment]
btw, as an FYI, there is also another way to configure openssl support in qt, which is `-openssl runtime`.  In this mode `QtNetwork.so` does not directly link to openssl, but tries to find it at runtime.  I assume that's how the qt binaries are distributed, because otherwise it'll error on any machine that doesn't have the correct version of openssl installed.  I haven't tried that mode yet because we can easily ensure that all of our machines have the proper yum package installed.
