### ISSUE TITLE
Segmentation Fault: rv.exe

### ISSUE THREAD

**Issue by edoardocarmignani** [AcademySoftwareFoundation/OpenRV#48]
Hello, after several attempts I managed to get rv.exe. At runtime, I get a segmentation fault. Digging a bit in the log I found that it failed to compile OperEXR.

<details>
<summary>An error example:</summary>

```
14>CustomBuild:
         C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DIMATH_DLL -DOPENEXR_DLL -DOPENEXR_EXPORTS -DOpenEXR_EXPORTS -IC:\OpenRV\_build\RV_DEPS_OPENEXR\src\src\lib\OpenEXR -IC:\OpenRV\_build\RV_DEPS_OPENEXR\src\cmake -IC:\OpenRV\_build\RV_DEPS_OPENEXR\src\src\lib\Iex -IC:\OpenRV\_build\RV_DEPS_OPENEXR\src\src\lib\IlmThread -external:IC:\OpenRV\_build\RV_DEPS_IMATH\install\include -external:IC:\OpenRV\_build\RV_DEPS_IMATH\install\include\Imath -external:IC:\OpenRV\_build\RV_DEPS_ZLIB\install\include -external:W0 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MD /O2 /Ob2 /DNDEBUG /EHsc /showIncludes /Fosrc\lib\OpenEXR\CMakeFiles\OpenEXR.dir\ImfVecAttribute.cpp.obj /Fdsrc\lib\OpenEXR\CMakeFiles\OpenEXR.dir\ /FS -c C:\OpenRV\_build\RV_DEPS_OPENEXR\src\src\lib\OpenEXR\ImfVecAttribute.cpp
    14>C:\OpenRV\_build\RV_DEPS_OPENEXR\src\src\lib\OpenEXR\ImfExport.h(1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM) [C:\OpenRV\_build\cmake\dependencies\RV_DEPS_OPENEXR.vcxproj]
    14>C:\OpenRV\_build\RV_DEPS_OPENEXR\src\src\lib\OpenEXR\ImfVecAttribute.cpp(22): error C2146: syntax error: missing ';' before identifier 'Vec2' [C:\OpenRV\_build\cmake\dependencies\RV_DEPS_OPENEXR.vcxproj]
```

</details>

The entire log of the build process (first errors around line 539):  [build.log](https://github.com/AcademySoftwareFoundation/OpenRV/files/10569823/build.log)

Here is the CMakeError for OpenEXR: [CMakeError_OpenEXR.log](https://github.com/AcademySoftwareFoundation/OpenRV/files/10569812/CMakeError_OpenEXR.log)

Thank you!

**Comment by rogernelson** [comment]
Hi @edoardocarmignani.  What command are you using to build? From the logs it looks like its using Ninja, which will use the gcc compiler instead of MSVC (required by some of the dependencies, particularly Qt). In the configure stage of the build, please make sure you have the `-G "Visual Studio 16 2019"` option.

You can see the recommended build commands here (bottom of the page):
https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/doc/build_system/config_windows.md

You can also use one of the provided aliases by doing these commands from the root of the repo, which will execute the commands from the build guide for you:
```
source rvcmds.sh
rvmk
```

**Comment by edoardocarmignani** [comment]
Hi, thanks for answering.
For this last build attempt, I have used aliases (`rvbootstrap` just to be sure to not miss any pip requirements)

Should I need to specify `-G` flag somewhere even with aliases?

**Comment by rogernelson** [comment]
No, the aliases should definitely take care of that.  Perhaps its just OpenEXR using Ninja, regardless of RV building with Visual Studio. 

From the build logs it is failing on trying to find a bunch of Linux-specific files (ucontext.h, pthread.h, etc), which is surprising since you're on Windows.  Did you run into this @bernie-laberge ?

**Comment by bernie-laberge** [comment]
Hello @edoardocarmignani, I was able to build successfully Open RV from scratch on windows.
I checked your build log and it looks like the OpenEXR lib was built successfully around lines 11800 (and I double checked that it perfectly matches my own config), but the error comes from line 541 ?
Perhaps there is a missing cmake dependency somewhere.
Have you tried running 'rvmk' again ? It might solve this issue.

**Comment by edoardocarmignani** [comment]
Hello @bernie-laberge, thank you for helping! 
If you mean running `rvmk` without cleaning the previous build, it gives me the same segmentation fault and this output:

[rebuild.log](https://github.com/AcademySoftwareFoundation/OpenRV/files/10668422/rebuild.log)

Maybe am I missing some libraries from the required installations? 
As soon as possible I will try again with a fresh vm.

**Comment by bernie-laberge** [comment]
OK so perhaps the OpenEXR errors in the original build log file was a red herring.
I would recommend building a debug build so you can debug the rv.exe using the Microsoft Visual Studio debugger.
Note that Open RV requires a vm with GPU support: could it be the source of your seg fault ?
You can build a debug version of Open RV with the following aliases:
`source ./rvcmds.sh
rvclean`

**Comment by bernie-laberge** [comment]
OK Thank you for the info @edoardocarmignani ! 
I will close this specific seg fault issue but I'll investigate the debug build issue that you had when I get the chance.
Thanks !
