### ISSUE TITLE
OpenRV not detecting blackmagic card

### ISSUE THREAD

**Issue by fjallraven** [AcademySoftwareFoundation/OpenRV#56]
In preferences OpenRV is not detecting blackmagic card but works in commercial RV.

Should this be working or not available in OpenRV?

Thank you

**Comment by bernie-laberge** [comment]
Hello @fjallraven,
Open RV does not currently support any video output cards at the moment because their implementation in the commercial version of RV were under commercial agreement with Blackmagic and AJA. 
But this is definitely on our radar. 
For a list of differences between Open RV and Commercial RV:

**Comment by fjallraven** [comment]
Thank you!
